### ISSUE TITLE
Interface for managing Grids

### ISSUE THREAD

**Issue by brunocanella** [grking/zoxel#27]
Add the possibility to the user manage his grids via the Qt interface.

Create some kind of table with the following columns: GridName, Plane, Offset, Visible, Color and Colision (Indicates ;

Let the user choose to add or remove new records to this table and also to modify the values of the columns. Then, reflect those changes to the scene.

**Comment by brunocanella** [comment]
Working on it o/

**Comment by grking** [comment]
Grids are working ok.
