### ISSUE TITLE
Color Picker could not pick red, yellow and purple block

### ISSUE THREAD

**Issue by mingchoi** [grking/zoxel#34]
Found this bug on v0.3.1 Windows Installer version.
Also, is there anyway to choose color by RBG value? I think the palette in the background color setting is better than the palette on the side bar. It is too hard to pick the color on my existing sketch.

**Comment by grking** [comment]
Colour picker is broken on windows it seems. Will fix.

**Comment by grking** [comment]
Yup, works for me on Windows now.
